services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ponder
      POSTGRES_PASSWORD: ponder_password
      POSTGRES_DB: ponder_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ponder-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ponder -d ponder_prod"]
      interval: 5s
      timeout: 5s
      retries: 5

  ponder:
    build: ./ponder
    command: npm run start
    environment:
      PONDER_DATABASE_URL: postgresql://ponder:ponder_password@postgres:5432/ponder_prod
      PONDER_RPC_URL_10143: ${PONDER_RPC_URL_10143}
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "42069:42069"
    networks:
      - ponder-network
    volumes:
      - ./ponder:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:42069/ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:

networks:
  ponder-network:
